CREATE TABLE task_org (
    ORG_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '支行ID',
    ORG_NAME VARCHAR(100) DEFAULT NULL COMMENT '支行名称',
    ORG1_ID VARCHAR(32) DEFAULT NULL COMMENT '支行机构号',
    PRIMARY KEY (ORG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支行表';